#define PROGRAM_VERSION 0.001
#define PROGRAM_NAME "OpenGL Renderer"
#define STRINGIFYANYTHING(x) STRINGIFY(x)
#define STRINGIFY(x) #x
#define PROGRAM_NAME_AND_VERSION PROGRAM_NAME " " STRINGIFYANYTHING(PROGRAM_VERSION)
